### ISSUE TITLE
errors in Copy nrpe configuration file on host task

### ISSUE THREAD

**Issue by kkoumantaros** [ARGOeu/argo-ansible#277]
TASK [commons : Copy nrpe configuration file on host] ****************************************************************************************************************************************************************
fatal: [snf-3500.ok-kno.grnetcloud.net]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'nrpe_conf_path' is undefined\n\nThe error appears to have been in '/Users/kkoum/lalakis/argo-ansible/roles/commons/tasks/is_monitored.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy nrpe configuration file on host\n  ^ here\n"}
fatal: [snf-3503.ok-kno.grnetcloud.net]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'nrpe_conf_path' is undefined\n\nThe error appears to have been in '/Users/kkoum/lalakis/argo-ansible/roles/commons/tasks/is_monitored.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy nrpe configuration file on host\n  ^ here\n"}
fatal: [snf-3501.ok-kno.grnetcloud.net]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'nrpe_conf_path' is undefined\n\nThe error appears to have been in '/Users/kkoum/lalakis/argo-ansible/roles/commons/tasks/is_monitored.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy nrpe configuration file on host\n  ^ here\n"}

**Comment by themiszamani** [comment]
nrpe_conf_path is undefined. It is yet added to the new ansible.
